name: space_survival
description: avoid comet or any other things cause the spaceship distroy

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flame: ^0.20.0
  uuid: ^2.0.4
  flame_splash_screen: ^0.0.1
  shared_preferences: ^0.5.7+3
  fluttertoast: ^4.0.1
  firebase_admob: ^0.9.3+2





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/vehicle/spaceship/ship_1.png
    - assets/images/vehicle/spaceship/ship_2.png
    - assets/images/vehicle/spaceship/ship_3.png
    - assets/images/vehicle/spaceship/ship_4.png
    - assets/images/vehicle/spaceship/gif/ship_5.gif
    - assets/images/vehicle/spaceship/withShield/ship1shield1.png
    - assets/images/vehicle/spaceship/withShield/ship1shield2.png
    - assets/images/vehicle/spaceship/withShield/ship1shield3.png
    - assets/images/vehicle/spaceship/withShield/ship1shield4.png
    - assets/images/vehicle/spaceship/gotHit/ship1GotHit1.png
    - assets/images/vehicle/spaceship/gotHit/ship1GotHit2.png
    - assets/images/vehicle/spaceship/gotHit/ship1GotHit3.png
    - assets/images/vehicle/spaceship/gotHit/ship1GotHit4.png
    - assets/images/vehicle/spaceship/gotHit/ship1GotHit5.png
    - assets/images/vehicle/spaceship/gotHit/ship1GotHit6.png
    - assets/images/vehicle/vertex/vertex1.png
    - assets/images/vehicle/vertex/vertex2.png
    - assets/images/vehicle/vertex/vertex3.png
    - assets/images/vehicle/vertex/vertex4.png
    - assets/images/vehicle/vertex/vertex5.png
    - assets/images/vehicle/vertex/gotHit/vertexGotHit1.png
    - assets/images/vehicle/vertex/gotHit/vertexGotHit2.png
    - assets/images/vehicle/vertex/gotHit/vertexGotHit3.png
    - assets/images/vehicle/vertex/gotHit/vertexGotHit4.png
    - assets/images/vehicle/vertex/gotHit/vertexGotHit5.png
    - assets/images/vehicle/vertex/gotHit/vertexGotHit6.png
    - assets/images/vehicle/vertex/withShield/vertexWithShield1.png
    - assets/images/vehicle/vertex/withShield/vertexWithShield2.png
    - assets/images/vehicle/vertex/withShield/vertexWithShield3.png
    - assets/images/vehicle/vertex/gif/vertextGif.gif
    - assets/images/vehicle/x-19/x-19_1.png
    - assets/images/vehicle/x-19/x-19_2.png
    - assets/images/vehicle/x-19/x-19_3.png
    - assets/images/vehicle/x-19/x-19_4.png
    - assets/images/vehicle/x-19/x-19_5.png
    - assets/images/vehicle/x-19/x-19_6.png
    - assets/images/vehicle/x-19/x-19_7.png
    - assets/images/vehicle/x-19/withShield/x-19WithShield1.png
    - assets/images/vehicle/x-19/withShield/x-19WithShield2.png
    - assets/images/vehicle/x-19/withShield/x-19WithShield3.png
    - assets/images/vehicle/x-19/withShield/x-19WithShield4.png
    - assets/images/vehicle/x-19/gotHit/x-19GotHit1.png
    - assets/images/vehicle/x-19/gotHit/x-19GotHit2.png
    - assets/images/vehicle/x-19/gotHit/x-19GotHit3.png
    - assets/images/vehicle/x-19/gotHit/x-19GotHit4.png
    - assets/images/vehicle/x-19/gif/x-19Gif.gif
    - assets/images/comet/rock/comet_1.png
    - assets/images/comet/rock/comet_2.png
    - assets/images/comet/rock/comet_3.png
    - assets/images/comet/rock/comet_4.png
    - assets/images/comet/rock/comet_5.png
    - assets/images/comet/rock/comet_6.png
    - assets/images/comet/rock/lock/comet_lock_1.png
    - assets/images/comet/rock/lock/comet_lock_2.png
    - assets/images/comet/rock/lock/comet_lock_3.png
    - assets/images/comet/rock/lock/comet_lock_4.png
    - assets/images/comet/rock/lock/comet_lock_5.png
    - assets/images/comet/rock/lock/comet_lock_6.png
    - assets/images/weapon/electric/electric_1.png
    - assets/images/weapon/electric/electric_2.png
    - assets/images/weapon/electric/electric_3.png
    - assets/images/weapon/electric/electric_4.png
    - assets/images/weapon/electric/electric_5.png
    - assets/images/weapon/electric/electric_6.png
    - assets/images/weapon/electric/electric_7.png
    - assets/images/weapon/electric/electric_8.png
    - assets/images/weapon/electric/electric_9.png
    - assets/images/weapon/electric/electric_10.png
    - assets/images/weapon/electric/electric_11.png
    - assets/images/weapon/dark/dark_1.png
    - assets/images/weapon/dark/dark_2.png
    - assets/images/weapon/dark/dark_3.png
    - assets/images/weapon/dark/dark_4.png
    - assets/images/weapon/dark/dark_5.png
    - assets/images/weapon/dark/dark_6.png
    - assets/images/weapon/dark/dark_7.png
    - assets/images/weapon/reload/reload_weapon_ready.png
    - assets/images/weapon/reload/reload_weapon_waiting.png
    - assets/images/weapon/reload/reload_weapon_1.png
    - assets/images/weapon/reload/reload_weapon_2.png
    - assets/images/weapon/reload/reload_weapon_3.png
    - assets/images/weapon/reload/reload_weapon_4.png
    - assets/images/weapon/reload/reload_weapon_5.png
    - assets/images/shield/shield_1.png
    - assets/images/heart/heart.png
    - assets/images/background/bg1.png
    - assets/images/background/bg_base.png
    - assets/images/background/bg_big_star.png
    - assets/images/background/bg_planet.png
    - assets/images/title/game_header.gif
    - assets/images/defeat/defeat.gif
    - assets/images/coin/coin.gif
    - assets/audio/sfx/comet_destroy.ogg
    - assets/audio/sfx/spaceship/sound_enable_shield.mp3
    - assets/audio/sfx/spaceship/sound_reload.mp3
    - assets/audio/bgm/bgm.mp3
    - assets/audio/bgm/bgm_route.mp3

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
